### PR TITLE
Handle both frontend and backend from the same server.

### PR DESCRIPTION
**Pull request by n1k0**
This patch makes the Express server the only server used to serve both the Web frontend and the API. That way, we can only rely on Scalingo hosting to server both, and benefit from review apps featuring a more coherent experience.

This will require to:

- [x] Ensure building both frontend and backend Elm apps before serving them
- [x] Update `openapi.yaml` to point at the new API server url
- [x] Disable Github pages
- [x] Remove the `deploy` npm command
- [x] Cleanup the `package.json` commands mess
- [x] Handle `/stats` to `/#/stats` redirect from the express webserver
- [x] Update README
- [ ] Update the [beta.gouv.fr Nginx configuration for Wikicarbone](https://github.com/betagouv/redirections/blob/master/servers.conf.erb#L167-L189) to point to the [Scalingo instance](https://dashboard.scalingo.com/apps/osc-fr1/wikicarbone/settings/domains/) (check with @tristanrobert) 

Ideally:
- [x] Launch a dev server with frontend + api auto-reload capabilities

### CODE REVIEW

**Comment by n1k0** [comment]
@tristanrobert Hello, if you're on holidays please disregard this comment :)

I need to update the current CNAME setup for `wikicarbone.beta.gouv.fr` to make it point at `wikicarbone.osc-fr1.scalingo.io` once this PR lands (so [this](https://wikicarbone-pr52.osc-fr1.scalingo.io/) will be served in production). 

We need to:
- Update the betagouv redirections accordingly here: https://github.com/betagouv/redirections/blob/master/servers.conf.erb#L167-L189
- Assign the `wikicarbone.beta.gouv.fr` domain to the Wikicarbone Scalingo instance, which is impossible right now because "the name is already taken". I think that may be because you've used it already in some Dashlord context?

image

Thanks in advance for your help if you're around, otherwise have a nice holiday!

**Review by tristanrobert — APPROVED** [review]

**Comment by tristanrobert** [comment]
Redirection supprimée du nginx beta

**Comment by n1k0** [comment]
Hmm merci @tristanrobert mais le site est cassé ; il manque l'a réattribution de la gestion du domaine `wikicarbone.beta.gouv.fr` à Scalingo, ce qui n'est pas possible actuellement :

image

J'imagine qu'il faut également modifier les enregistrements DNS en conséquence, ce sur quoi je n'ai pas la main… Tu peux regarder ? Merci :)

**Comment by n1k0** [comment]
@tristanrobert J'ai créé une PR pour tenter de rétablir le proxy_pass sur le dépôt redirection : https://github.com/betagouv/redirections/pull/29

Si tu peux regarder et éventuellement valider et merger, c'est top :)

**Comment by n1k0** [comment]
@tristanrobert C'est bon https://github.com/betagouv/redirections/pull/29 a été mergée et l'incident est clos.

**Pull request merged**
