### PR TITLE
Implement all 15 target impacts.

### PR DESCRIPTION
**Pull request by paulboosz**

### CODE REVIEW

**Comment by n1k0** [comment]
Thanks @paulboosz, I'm gonna take over the patch to update the code in order to handle the newly introduced trigrams.

**Review by n1k0 — COMMENTED** [review]
Thanks @paulboosz, I'm gonna take over the patch to update the code in order to handle the newly introduced trigrams.

**Review by n1k0 — COMMENTED** [review]
@paulboosz Just a note, I see we now have 15 impacts listed, while the PR title mentions we should have 16. Is that expected?

**Comment by paulboosz** [comment]
@n1k0 indeed there's an error in the PR name, should be "add-15-impacts"

**Comment by n1k0** [comment]
We should probably take some time to ensure everything is working file after this patch: https://wikicarbone.beta.gouv.fr/branches/add_16_impacts/#/simulator

**Review by magopian — APPROVED** [review]
I glazed over the "search and replace", and had a quick look at the code related to http errors, all looks good to me ;)

**Comment by n1k0** [comment]
I landed this patch, we'll file another PR to implement remaining work and ease reviews.

**Pull request merged**
